
package pl.soa.parkometer.carpark_mock.soap_client.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SpotService", targetNamespace = "http://soap.parkometer.soa.pl/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SpotService {


    /**
     * 
     * @return
     *     returns SpotArray
     */
    @WebMethod
    @WebResult(name = "getFreeSpotsResponse", partName = "getFreeSpotsResponse")
    public SpotArray getFreeSpots();

    /**
     * 
     * @param spot
     */
    @WebMethod
    public void updateSpot(
        @WebParam(name = "Spot", partName = "Spot")
        Spot spot);

}
